uint8 id
bool set_torque
bool torque_enable
bool set_mode
uint8 mode
bool set_position
int16 position
uint8 acc
uint16 speed
---
bool success
int16 current_position
uint8 current_voltage
uint8 current_temperature
uint8 current_mode