depth:
  offset:
  - -0.012
  - 0.0
  - -0.005
  scale:
  - 1.0
  - 1.0
  - 1.0
kinematics:
  offset:
  - -0.008
  - 0.0
  - 0.0
  scale:
  - 1.0
  - 1.0
  - 1.0
pixel:
  offset:
  - -0.02000000000000002
  - -0.006
  - 0.0
  scale:
  - 1.0
  - 1.0
  - 1.0
